// Generated by CoffeeScript 2.2.1
(function() {
  this.COMPILERS = [
    /*{
      // Assembler
      name: 'FASM',
      source: 'Assembly',
      target: 'Machine Code',
      type: 'Assembler',
      url: 'https://flatassembler.net/'
    },*/
    {
      name: 'Literate.jl',
      source: 'Julia Script (Literate)',
      target: 'Markdown (GFM)',
      type: 'Literate Programming',
      url: 'https://fredrikekre.github.io/Literate.jl/latest/'
    },
    {
      name: 'Literate.jl',
      source: 'Julia Script (Literate)',
      target: 'Markdown (Documentor.jl)',
      type: 'Literate Programming',
      url: 'https://fredrikekre.github.io/Literate.jl/latest/'
    },
    {
      name: 'Literate.jl',
      source: 'Julia Script (Literate)',
      target: 'JuPyTer Notebook',
      type: 'Literate Programming',
      url: 'https://fredrikekre.github.io/Literate.jl/latest/'
    },
	{
      name: 'Literate.jl',
      source: 'Julia Script (Literate)',
      target: 'Julia Script (Plain)',
      type: 'Literate Programming',
      url: 'https://fredrikekre.github.io/Literate.jl/latest/'
    },

  ];

}).call(this);
