// Generated by CoffeeScript 2.2.1
(function() {
  this.COMPILERS = [
    /*{
      // Assembler
      name: 'FASM',
      source: 'Assembly',
      target: 'Machine Code',
      type: 'Assembler',
      url: 'https://flatassembler.net/'
    },*/
    {
      name: 'Literate.jl',
      sources: ['Script (Literate)'],
      targets: ['Markdown (GFM)', 'Markdown (Documenter.jl)', 'Jupyter Notebook', 'Script (Plain)'],
      type: 'Literate Programming',
      url: 'https://fredrikekre.github.io/Literate.jl/latest/'
    },
    {
      name: 'Documenter.jl',
      sources: ['Markdown (Documenter.jl)'],
      targets: ['Markdown (GFM)', 'HTML', 'PDF'],
      type: 'Documentation Generation',
      url: 'https://juliadocs.github.io/Documenter.jl'
    },
	{
      name: 'MkDocs',
      sources: ['Markdown (GFM)'],
      targets: ['HTML'],
      type: 'Documentation Generation',
      url: 'https://www.mkdocs.org/'
    },
	{
	 name: 'nbconvert (default)',
	 type: 'nbconvert',
	 sources: ['Jupyter Notebook'],
	 targets: ['HTML', 'LaTeX', 'PDF', 'Reveal JS', 'Markdown (GFM)', 'ReStructured Text', 'Script (Plain)'],
	 url: 'https://github.com/jupyter/nbconvert'
	},
	{
	 name: 'nbconvert (WeaveAwayNotebooks)',
	 type: 'nbconvert',
	 sources: ['Jupyter Notebook'],
	 targets: ['Script (Literate)'],
	 url: 'https://github.com/oxinabox/WeaveAwayNotebooks'
	},
	{
	 name: 'nbconvert (Jekyll)',
	 type: 'nbconvert',
	 sources: ['Jupyter Notebook'],
	 targets: ['Markdown (Jekyll)'],
	 url: 'https://github.com/oxinabox/oxinabox.github.io/tree/master/scripts/jupyter'
	},
	{
	 name: 'Print to PDF',
	 type: 'Printer',
	 sources: ['HTML', 'Jupyter Notebook'],
	 targets: ['PDF'],
	 url: ''
	},
	{
	 name: 'LuaLaTeX',
	 type: 'TeX',
	 sources: ['LaTeX'],
	 targets: ['PDF'],
	},
  ];

}).call(this);
